include:
- project: 'nse/ci'
  file:
    - /ci/lib/tox-bb5.yml
    - /ci/jobs/check-version.yml
    - /ci/jobs/lint.yml
    - /ci/jobs/py37.yml
    - /ci/jobs/py38.yml
    - /ci/jobs/py39.yml
    - /ci/jobs/docs.yml
    - /ci/jobs/coverage.yml
    - /ci/jobs/build-package.yml
    - /ci/jobs/publish-package.yml
    - /ci/jobs/tag.yml

.tox-template:
  tags: [bb5_map]
  variables:
    EXTRA_MODULES:
      unstable:cmake
      unstable:gcc/11.2.0

py37:
  extends: .tox-template
  variables:
    EXTRA_MODULES:
      unstable:cmake
      archive/2020-12:gcc/8.3.0

py38:
  extends: .tox-template
  variables:
    EXTRA_MODULES:
      unstable:cmake
      archive/2020-12:gcc/9.3.0

functional-tests:
  extends: .tox-template
  variables:
    TOXENV: functional
