include:
- project: 'nse/ci'
  ref: main
  file:
    - /ci/lib/tox-bb5.yml
    - /ci/jobs/check-version.yml
    - /ci/jobs/lint.yml
    - /ci/jobs/py36.yml
    - /ci/jobs/coverage.yml
    - /ci/jobs/build-package.yml
    - /ci/jobs/publish-package.yml
    - /ci/jobs/tag.yml

.tox-template:
  tags: [bb5]
  variables:
    EXTRA_MODULES:
      archive/2019-12:gcc
      archive/2019-12:cmake/3.13.0



functional-tests:
  extends: .tox-template
  variables:
    TOXENV: functional
