include:
- project: 'nse/ci'
  file:
    - /ci/lib/tox-bb5.yml
    - /ci/jobs/check-version.yml
    - /ci/jobs/lint.yml
    - /ci/jobs/py38.yml
    - /ci/jobs/docs.yml
    - /ci/jobs/coverage.yml
    - /ci/jobs/build-package.yml
    - /ci/jobs/publish-package.yml
    - /ci/jobs/tag.yml

.tox-template:
  tags: [bb5_map]
  variables:
    EXTRA_MODULES:
      archive/2021-05:cmake

functional-tests:
  extends: .tox-template
  variables:
    TOXENV: functional
